let setting1 = [
    {"id": "1-1", "category": "A", "taken": true},
    {"id": "1-2", "category": "A", "taken": true},
    {"id": "1-3", "category": "A", "taken": true},
    {"id": "1-4", "category": "A", "taken": true},
    {"id": "1-5", "category": "A", "taken": true},
    {"id": "1-6", "category": "A", "taken": true},
    {"id": "2-1", "category": "A", "taken": true},
    {"id": "2-2", "category": "A", "taken": true},
    {"id": "2-3", "category": "A", "taken": true},
    {"id": "2-4", "category": "A", "taken": true},
    {"id": "2-5", "category": "A", "taken": true},
    {"id": "2-6", "category": "A", "taken": true},
    {"id": "3-1", "category": "A", "taken": true},
    {"id": "3-2", "category": "A", "taken": true},
    {"id": "3-3", "category": "A", "taken": true},
    {"id": "3-4", "category": "A", "taken": true},
    {"id": "3-5", "category": "A", "taken": true},
    {"id": "3-6", "category": "A", "taken": true},
    {"id": "4-1", "category": "B", "taken": true},
    {"id": "4-2", "category": "B", "taken": false},
    {"id": "4-3", "category": "B", "taken": false},
    {"id": "4-4", "category": "B", "taken": false},
    {"id": "4-5", "category": "B", "taken": false},
    {"id": "4-6", "category": "B", "taken": false},
    {"id": "5-1", "category": "B", "taken": false},
    {"id": "5-2", "category": "B", "taken": true},
    {"id": "5-3", "category": "B", "taken": false},
    {"id": "5-4", "category": "B", "taken": false},
    {"id": "5-5", "category": "B", "taken": false},
    {"id": "5-6", "category": "B", "taken": false},
];

let setting2 = [
    {"id": "1-1", "category": "A", "taken": false},
    {"id": "1-2", "category": "A", "taken": false},
    {"id": "1-3", "category": "A", "taken": false},
    {"id": "1-4", "category": "A", "taken": false},
    {"id": "1-5", "category": "A", "taken": false},
    {"id": "1-6", "category": "A", "taken": false},
    {"id": "2-1", "category": "A", "taken": false},
    {"id": "2-2", "category": "A", "taken": false},
    {"id": "2-3", "category": "A", "taken": true},
    {"id": "2-4", "category": "A", "taken": true},
    {"id": "2-5", "category": "A", "taken": true},
    {"id": "2-6", "category": "A", "taken": true},
    {"id": "3-1", "category": "A", "taken": false},
    {"id": "3-2", "category": "A", "taken": false},
    {"id": "3-3", "category": "A", "taken": true},
    {"id": "3-4", "category": "A", "taken": false},
    {"id": "3-5", "category": "A", "taken": false},
    {"id": "3-6", "category": "A", "taken": false},
    {"id": "4-1", "category": "A", "taken": true},
    {"id": "4-2", "category": "A", "taken": false},
    {"id": "4-3", "category": "A", "taken": false},
    {"id": "4-4", "category": "A", "taken": false},
    {"id": "4-5", "category": "A", "taken": false},
    {"id": "4-6", "category": "A", "taken": true},
    {"id": "5-1", "category": "B", "taken": true},
    {"id": "5-2", "category": "B", "taken": false},
    {"id": "5-3", "category": "B", "taken": false},
    {"id": "5-4", "category": "B", "taken": true},
    {"id": "5-5", "category": "B", "taken": true},
    {"id": "5-6", "category": "B", "taken": true},
];

let setting3 = {};
let setting4 = {};
let setting5 = {};

export { setting1, setting2 };